# Site settings
title: Missouri S&T SeNDeComp
email: sedighs@mst.edu
description: ""
baseurl: "/~sendecomp"
url: "http://web.mst.edu/~sendecomp"
encoding: ISO-8859-1

# Build settings
markdown: kramdown
permalink: pretty
