# Site settings
title: Missouri S&T SeNDeComp
email: tjm6f4@mst.edu
description: ""
baseurl: ""
url: "http://web.mst.edu/~sendecomp"
encoding: ISO-8859-1

# Build settings
markdown: kramdown
permalink: pretty
